import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'
import tsconfigPaths from 'vite-tsconfig-paths'
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'

const root = fileURLToPath(new URL('.', import.meta.url))

export default defineConfig({
  plugins: [
    vue(),
    tsconfigPaths(),
  ],
  resolve: {
    alias: {
      '~': resolve(root, 'app'),
      '@': resolve(root, 'app'),
    },
  },
  test: {
    environment: 'node',
    globals: true,
    include: ['tests/**/*.test.ts', 'tests/**/*.spec.ts'],
    exclude: ['tests/firebase/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      thresholds: {
        statements: 75,
        branches: 70,
        functions: 80,
        lines: 75,
      },
      // Lista esplicita: solo i file che hanno test associati.
      // Aggiungere qui ogni nuovo file quando si scrivono i suoi test.
      // Questo rende le thresholds un contratto verificabile, non un numero illusorio.
      include: [
        // ── Phase 1–2: services e utils ──────────────────────────────────
        'app/config/firebaseRuntimeTarget.ts',
        'app/services/auth/authService.ts',
        'app/services/auth/userProvisioningService.ts',
        'app/services/auth/localIdentityBridge.ts',
        'app/composables/useConfirmedLogout.ts',
        'app/config/optimalShiftRpm.ts',
        'app/services/gateway/activityProjectionBuilders.ts',
        'app/services/gateway/bestTimesBuilders.ts',
        'app/services/gateway/trackDetailProjectionBuilder.ts',
        'app/services/monitoring/clientHeartbeatService.ts',
        'app/services/monitoring/clientRuntimeReportingService.ts',
        'app/services/monitoring/clientDiagnosticsService.ts',
        'app/repositories/adminCockpitRepository.ts',
        'app/repositories/clientDiagnosticsRepository.ts',
        'app/services/projections/trackBestProjectionGuard.ts',
        'app/services/runtime/runtimeBootstrapPolicy.ts',
        'app/services/runtime/runtimeBootstrapCoordinator.ts',
        'app/services/runtime/runtimeCompatibilityCache.ts',
        'app/services/runtime/rendererRuntimeBootstrapAdapter.ts',
        'app/services/runtime/runtimeWindowBridge.ts',
        'app/services/session-detail/sessionMath.ts',
        'app/services/session-detail/sessionLapSeries.ts',
        'app/services/sync/firebaseStructureHealthService.ts',
        'app/services/sync/canonicalMigrationCheckpoint.ts',
        'app/services/sync/autoSyncController.ts',
        'app/services/sync/ownerDataRepairService.ts',
        'app/services/sync/sessionUploadService.ts',
        'app/services/sync/syncTriggerPolicy.ts',
        'app/services/telemetry/lapTraceChart.ts',
        'app/services/telemetry/raceFuelClassification.ts',
        'app/services/telemetry/sessionMergeLogic.ts',
        'app/services/telemetry/theoreticalTimesCalculator.ts',
        'app/services/overlay/tyreSetupViewModel.ts',
        'app/services/overlay/standingsCarNumber.ts',
        'app/services/overlay/standingsLayout.ts',
        'app/services/overlay/standingsPresentation.ts',
        'app/services/overlay/spectatorTelemetry.ts',
        'app/services/overlay/standingsHighlightTracker.ts',
        'app/services/audio/audioPlayback.ts',
        'app/services/spotter/coachVoiceController.ts',
        'app/services/spotter/trackVoiceReferences.ts',
        'app/services/spotter/trackVoiceReferenceRuntime.ts',
        'app/services/spotter/trackVoiceReferenceChanges.ts',
        'app/services/spotter/spotterSessionPolicy.ts',
        'app/utils/firestoreSanitize.ts',
        'app/utils/diagnosticsPresentation.ts',
        'app/utils/featureAccess.ts',
        'app/utils/authRouteGuard.ts',
        'app/utils/tyreSlipPresentation.ts',
        'app/utils/tyreTemperaturePresentation.ts',
        'app/utils/dashboardPresentation.ts',
        'app/utils/infoPresentation.ts',
        'app/utils/hudOverlayWindow.ts',
        'app/utils/sectorDeltaPresentation.ts',
        'app/utils/completedLapHold.ts',
        'app/utils/hudOverlayPresentationCapabilities.ts',
        'app/utils/hudOverlayBackground.ts',
        'app/utils/hudRoutePerformance.ts',
        'app/utils/brakeTemperaturePresentation.ts',
        'app/utils/brakeAxlePresentation.ts',
        'app/utils/sessionParser.ts',
        'app/utils/raceCalendarCountdown.ts',
        'server/utils/chatterboxRuntimeStatus.ts',
        'server/utils/chatterboxVoiceCatalog.ts',
        'shared/chatterboxProsody.ts',
        'server/utils/kokoroRuntimeStatus.ts',
        'server/utils/trackVoicePointMerge.ts',
        'server/utils/voiceScriptNormalize.ts',
        'server/utils/coachVoiceScriptValidate.ts',
        // ── Phase 3: composables ─────────────────────────────────────────
        'app/composables/useLiveStatePoller.ts',
        'app/composables/useSpotterVoiceSettings.ts',
        'app/composables/useFastStatePoller.ts',
        'app/composables/useCompletedLapHold.ts',
        'app/composables/useHudOverlayBackground.ts',
        'app/composables/useStandingsState.ts',
        'app/composables/useOverlayTelemetrySource.ts',
        'app/composables/useStandingsHighlights.ts',
        'app/composables/useTimedHudPager.ts',
        'app/composables/useSessionOrchestrator.ts',
        'app/composables/useCoachInsights.ts',
        'app/composables/useRuntimeCapabilityGate.ts',
        // ── Phase 4: composables estratti da useTelemetryData ────────────
        'app/composables/useSessionLoader.ts',
        'app/composables/useSessionSharing.ts',
        'app/composables/useTrackBests.ts',
        // ── PIP-175: overlay HUD multipli ────────────────────────────────
        'app/composables/useHudOverlay.ts',
        'app/composables/useOverlayInteractionRegions.ts',
        'app/composables/useOverlayInteractionContract.ts',
      ],
    },
  },
})
