param(
  [switch]$WhatIf
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$removed = New-Object System.Collections.Generic.List[string]
$skipped = New-Object System.Collections.Generic.List[string]

function Test-InRepo {
  param([string]$Path)
  $resolved = (Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path
  return ($resolved -eq $repoRoot -or $resolved.StartsWith($repoRoot + [System.IO.Path]::DirectorySeparatorChar))
}

function Remove-RepoItem {
  param(
    [string]$Path,
    [switch]$Recurse
  )

  if (-not (Test-Path -LiteralPath $Path)) {
    return
  }

  $resolved = (Resolve-Path -LiteralPath $Path).Path
  if (-not (Test-InRepo -Path $resolved)) {
    $skipped.Add("outside repo: $resolved")
    return
  }

  if ($WhatIf) {
    $removed.Add("would remove: $resolved")
    return
  }

  try {
    if ($Recurse) {
      Get-ChildItem -LiteralPath $resolved -Recurse -Force -ErrorAction SilentlyContinue |
        ForEach-Object {
          try { $_.Attributes = "Normal" } catch {}
        }
      Remove-Item -LiteralPath $resolved -Recurse -Force -ErrorAction Stop
    } else {
      try { (Get-Item -LiteralPath $resolved -Force).Attributes = "Normal" } catch {}
      Remove-Item -LiteralPath $resolved -Force -ErrorAction Stop
    }
  } catch {
    $skipped.Add("locked or denied: $resolved :: $($_.Exception.Message)")
    return
  }
  $removed.Add($resolved)
}

# Codex/browser/tool scratch directories.
foreach ($dir in @(".codex-tmp", ".codex_tmp", ".codex_pycache")) {
  Remove-RepoItem -Path (Join-Path $repoRoot $dir) -Recurse
}

# Python cache generated by local checks.
Get-ChildItem -LiteralPath $repoRoot -Directory -Recurse -Force -Filter "__pycache__" -ErrorAction SilentlyContinue |
  ForEach-Object {
    Remove-RepoItem -Path $_.FullName -Recurse
  }

# Known Codex probe files: 8-char random names, 4 bytes, exact content "blat".
Get-ChildItem -LiteralPath $repoRoot -File -Force -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -match "^[a-z0-9_]{8}$" -and $_.Length -eq 4 } |
  ForEach-Object {
    $content = Get-Content -LiteralPath $_.FullName -Raw -ErrorAction SilentlyContinue
    if ($content -eq "blat") {
      Remove-RepoItem -Path $_.FullName
    }
  }

# Root-level generated smoke audio. Real app voice assets live under nuxt/public/voice.
foreach ($file in @("kokoro_test.wav", "kokoro_energy_test.wav", "kokoro_speed_15_test.wav", "qualifying_voice_smoke.wav")) {
  Remove-RepoItem -Path (Join-Path $repoRoot $file)
}

# Legacy one-off bytecode artifact found at repo root.
$legacyBytecode = Join-Path $repoRoot "q"
if (Test-Path -LiteralPath $legacyBytecode) {
  $bytes = [System.IO.File]::ReadAllBytes($legacyBytecode)
  $textProbe = [System.Text.Encoding]::GetEncoding(28591).GetString($bytes)
  $looksLikeLauncherBytecode = $bytes.Length -gt 16 -and $textProbe.Contains("launcher.py") -and $textProbe.Contains("ACC Suite Launcher")
  if ($looksLikeLauncherBytecode) {
    Remove-RepoItem -Path $legacyBytecode
  }
}

Write-Output "Removed entries: $($removed.Count)"
$removed | ForEach-Object { Write-Output "  $_" }
if ($skipped.Count -gt 0) {
  Write-Output "Skipped entries: $($skipped.Count)"
  $skipped | ForEach-Object { Write-Output "  $_" }
}
