// @vitest-environment jsdom
import { mount, flushPromises } from '@vue/test-utils'
import { ref } from 'vue'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import Calendar from '~/components/overview/UpcomingRacesCard.vue'
import Activity from '~/components/cards/ActivityCard.vue'
import { overviewEntryKey } from '~/services/auth/overviewEntryPreparation'

const mocks = vi.hoisted(() => ({ load: vi.fn(), create: vi.fn(), update: vi.fn(), remove: vi.fn() }))
vi.mock('~/composables/useFirebaseAuth', () => ({ useFirebaseAuth: () => ({ currentUser: ref({ uid: 'qa' }), userRole: ref('pilot') }) }))
vi.mock('~/composables/useRuntimeCapabilityGate', () => ({ useRuntimeCapabilityGate: () => ({ gate: () => ref({ allowed: true }) }) }))
vi.mock('~/repositories/raceCalendarRepository', () => ({ loadRaceCalendarEvents: mocks.load, createRaceCalendarEvent: mocks.create, updateRaceCalendarEvent: mocks.update, deleteRaceCalendarEvent: mocks.remove }))
const event = { id: 'event', title: 'Gara QA', startsAt: '2099-10-01T19:00', trackName: 'Monza', carName: 'Ferrari' }
beforeEach(() => { vi.clearAllMocks(); mocks.load.mockResolvedValue([event]) })

describe('racing overview components', () => {
  it('reuses the calendar request prepared for the same user and retries after failure', async () => {
    const pending = Promise.reject(new Error('offline'))
    const entry = ref({ takeEvents: vi.fn().mockReturnValueOnce(pending) })
    const wrapper = mount(Calendar, { props: { userId: 'qa', racing: true }, global: { provide: { [overviewEntryKey as symbol]: entry } } })
    await flushPromises()
    expect(mocks.load).not.toHaveBeenCalled()
    expect(wrapper.text()).toContain('Calendario non disponibile')
    await wrapper.get('.race-empty button').trigger('click')
    await flushPromises()
    expect(mocks.load).toHaveBeenCalledOnce()
    expect(wrapper.text()).toContain('Gara QA')
    wrapper.unmount()
  })
  it('does not consume another user prepared calendar', async () => {
    const wrapper = mount(Calendar, { props: { userId: 'qa', racing: true }, global: { provide: { [overviewEntryKey as symbol]: ref({ takeEvents: (uid: string) => uid === 'other' ? Promise.resolve([]) : undefined }) } } })
    await flushPromises()
    expect(mocks.load).toHaveBeenCalledWith('qa', 25)
    expect(wrapper.text()).toContain('Gara QA')
    wrapper.unmount()
  })
  it('opens the existing create form, validates and persists through the repository', async () => {
    const wrapper = mount(Calendar, { props: { userId: 'qa', racing: true }, global: { stubs: { teleport: true } } })
    await flushPromises()
    expect(wrapper.get('[aria-label="Aggiungi gara"] svg circle').exists()).toBe(true)
    expect(wrapper.get('[aria-label="Opzioni prossima gara"] svg').exists()).toBe(true)
    await wrapper.get('[aria-label="Aggiungi gara"]').trigger('click')
    const errorSlot = wrapper.get('.race-error-slot--reserved').element
    expect(wrapper.find('.form-error').exists()).toBe(false)
    await wrapper.get('form').trigger('submit')
    expect(wrapper.get('.race-error-slot--reserved').element).toBe(errorSlot)
    expect(wrapper.get('.race-error-slot--reserved').attributes('aria-live')).toBe('polite')
    expect(wrapper.text()).toContain('Titolo, data e pista sono obbligatori')
    const fields = wrapper.findAll('input')
    await fields[0]!.setValue('Nuova gara')
    await fields[1]!.setValue('2099-10-02T18:00')
    await fields[2]!.setValue('Spa')
    await fields[3]!.setValue('Ferrari 296 GT3')
    await fields[4]!.setValue('https://www.thesimgrid.com/championships/123')
    await fields[5]!.setValue('https://example.com/race')
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(mocks.create).toHaveBeenCalledWith('qa', expect.objectContaining({ title: 'Nuova gara', trackName: 'Spa', carName: 'Ferrari 296 GT3', simGridUrl: 'https://www.thesimgrid.com/championships/123', raceUrl: 'https://example.com/race' }))
    expect(wrapper.find('form').exists()).toBe(false)
    wrapper.unmount()
  })
  it('offers edit and delete from the race menu, retaining confirmation', async () => {
    const wrapper = mount(Calendar, { props: { userId: 'qa', racing: true }, global: { stubs: { teleport: true } } })
    await flushPromises()
    await wrapper.get('.race-options__menu button').trigger('click')
    expect((wrapper.get('input').element as HTMLInputElement).value).toBe('Gara QA')
    await wrapper.get('input').setValue('Gara aggiornata')
    await wrapper.get('form').trigger('submit'); await flushPromises()
    expect(mocks.update).toHaveBeenCalledWith('qa', 'event', expect.objectContaining({ title: 'Gara aggiornata' }))
    await wrapper.findAll('.race-options__menu button')[1]!.trigger('click')
    expect(mocks.remove).not.toHaveBeenCalled()
    await wrapper.get('[aria-label="Chiudi"]').trigger('click')
    expect(mocks.remove).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('cancels a partially completed form without persisting and reopens empty', async () => {
    const wrapper = mount(Calendar, { props: { userId: 'qa', racing: true }, global: { stubs: { teleport: true } } })
    await flushPromises()
    await wrapper.get('[aria-label="Aggiungi gara"]').trigger('click')
    await wrapper.get('input').setValue('Bozza da annullare')
    await wrapper.get('footer .secondary-action').trigger('click')
    expect(wrapper.find('form').exists()).toBe(false)
    expect(mocks.create).not.toHaveBeenCalled()
    await wrapper.get('[aria-label="Aggiungi gara"]').trigger('click')
    expect((wrapper.get('input').element as HTMLInputElement).value).toBe('')
    await wrapper.get('form').trigger('keydown', { key: 'Escape' })
    expect(wrapper.find('form').exists()).toBe(false)
    wrapper.unmount()
  })
  it('shows seven calendar days with real zero values and matching totals', () => {
    const wrapper = mount(Activity, { props: { racing: true, data: Array.from({ length: 7 }, (_, i) => ({ day: `D${i}`, dateLabel: `${i + 1}/09`, practice: i === 0 ? 28 : 0, qualify: 0, race: 0 })), practiceTotal: { minutes: 28, sessions: 1 }, qualifyTotal: { minutes: 0, sessions: 0 }, raceTotal: { minutes: 0, sessions: 0 } } })
    expect(wrapper.findAll('.bar-column')).toHaveLength(7)
    expect(wrapper.findAll('.bar-total').map(x => x.text())).toEqual(['28min', '0', '0', '0', '0', '0', '0'])
    expect(wrapper.get('.legend-item--practice').text()).toContain('28')
    wrapper.unmount()
  })
})
